CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    name_norm VARCHAR(64) NOT NULL,
    invite_code VARCHAR(64) NOT NULL UNIQUE,
    created_by BIGINT,
    created_at BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT groups_name_nonempty CHECK (length(btrim(name)) > 0),
    CONSTRAINT groups_name_norm_normalized CHECK (name_norm = lower(btrim(name_norm))),
    CONSTRAINT groups_name_norm_nonempty CHECK (length(name_norm) > 0),
    CONSTRAINT groups_invite_code_nonempty CHECK (length(invite_code) > 0),
    CONSTRAINT groups_version_nonnegative CHECK (version >= 0)
);

CREATE INDEX groups_name_norm_idx ON groups (name_norm);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    created_at BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT group_members_group_user_unique UNIQUE (group_id, user_id),
    CONSTRAINT group_members_role_allowed CHECK (role IN ('admin', 'member')),
    CONSTRAINT group_members_version_nonnegative CHECK (version >= 0)
);

CREATE INDEX group_members_group_id_idx ON group_members (group_id);
CREATE INDEX group_members_user_id_idx ON group_members (user_id);
