CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password_hash VARCHAR(255),
    username VARCHAR(32),
    display_name VARCHAR(255),
    is_guest BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    theme VARCHAR(20) NOT NULL DEFAULT 'light',
    locale VARCHAR(10) NOT NULL DEFAULT 'en',
    created_at BIGINT NOT NULL,
    email_verified_at BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT users_guest_credentials CHECK (
        NOT is_guest OR (email IS NULL AND password_hash IS NULL AND email_verified_at IS NULL)
    ),
    CONSTRAINT users_email_normalized CHECK (
        email IS NULL OR email = lower(btrim(email))
    ),
    CONSTRAINT users_username_normalized CHECK (
        username IS NULL OR username = lower(btrim(username))
    ),
    CONSTRAINT users_username_nonempty CHECK (
        username IS NULL OR length(username) > 0
    ),
    CONSTRAINT users_username_no_at CHECK (
        username IS NULL OR position('@' IN username) = 0
    ),
    CONSTRAINT users_theme_allowed CHECK (theme IN ('light', 'dark')),
    CONSTRAINT users_version_nonnegative CHECK (version >= 0)
);

CREATE UNIQUE INDEX users_email_unique_idx ON users (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX users_username_unique_idx ON users (username) WHERE username IS NOT NULL;
