CREATE TABLE login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    user_id BIGINT,
    ip VARCHAR(64),
    outcome VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX login_attempts_email_created_at_idx ON login_attempts (email, created_at);
CREATE INDEX login_attempts_user_id_idx ON login_attempts (user_id);
CREATE INDEX login_attempts_created_at_idx ON login_attempts (created_at);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at BIGINT NOT NULL,
    actor_user_id BIGINT,
    actor_email VARCHAR(255),
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(32),
    target_id VARCHAR(64),
    detail VARCHAR(1000),
    ip VARCHAR(64)
);

CREATE INDEX audit_log_occurred_at_idx ON audit_log (occurred_at);
CREATE INDEX audit_log_actor_user_id_idx ON audit_log (actor_user_id);
CREATE INDEX audit_log_target_idx ON audit_log (target_type, target_id);

CREATE TABLE usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL,
    method VARCHAR(8) NOT NULL,
    route VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    user_id BIGINT,
    ip VARCHAR(64),
    CONSTRAINT usage_events_method_nonempty CHECK (length(method) > 0),
    CONSTRAINT usage_events_route_nonempty CHECK (length(route) > 0),
    CONSTRAINT usage_events_route_without_query CHECK (position('?' IN route) = 0),
    CONSTRAINT usage_events_status_valid CHECK (status BETWEEN 100 AND 599)
);

CREATE INDEX usage_events_created_at_idx ON usage_events (created_at);
CREATE INDEX usage_events_route_created_at_idx ON usage_events (route, created_at);
CREATE INDEX usage_events_user_id_created_at_idx ON usage_events (user_id, created_at);
